"""Refatorar modelos para corresponder ao esquema do etapa1.txt

Revision ID: 27459e23a5a0
Revises: 
Create Date: 2025-11-19 06:48:47.190134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = '27459e23a5a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get current connection and inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old tables conditionally
    if inspector.has_table('desempenho_simulados'):
        op.drop_table('desempenho_simulados')
    if inspector.has_table('respostas_alunos'):
        op.drop_table('respostas_alunos')
    if inspector.has_table('questoes'):
        op.drop_table('questoes')
    if inspector.has_table('matriculas'):
        op.drop_table('matriculas')
    if inspector.has_table('simulados'):
        op.drop_table('simulados')
    if inspector.has_table('usuarios'):
        op.drop_table('usuarios')

    # Re-create tables (Alembic's autogen will handle this part)
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ra', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ra')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('senha_acesso', sa.String(length=50), nullable=False),
    sa.Column('texto_base', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade_questoes', sa.Integer(), nullable=True),
    sa.Column('tempo_limite', sa.Integer(), nullable=True),
    sa.Column('disponivel_ate', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'materia_id', name='_aluno_materia_uc')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('opcoes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resposta_correta', sa.String(length=10), nullable=False),
    sa.Column('nivel_dificuldade', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desempenho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('total_questoes', sa.Integer(), nullable=True),
    sa.Column('acertos', sa.Integer(), nullable=True),
    sa.Column('nota_final', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tempo_total', sa.Integer(), nullable=True),
    sa.Column('data_conclusao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas_alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('resposta_aluno', sa.String(length=500), nullable=False),
    sa.Column('correta', sa.BOOLEAN(), nullable=True),
    sa.Column('nota', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('feedback_ia', sa.Text(), nullable=True),
    sa.Column('tempo_resposta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Add indexes as per etapa1.txt
    op.create_index('idx_inscricoes_aluno', 'inscricoes', ['aluno_id'], unique=False)
    op.create_index('idx_inscricoes_materia', 'inscricoes', ['materia_id'], unique=False)
    op.create_index('idx_questoes_materia', 'questoes', ['materia_id'], unique=False)
    op.create_index('idx_respostas_aluno', 'respostas_alunos', ['aluno_id'], unique=False)
    op.create_index('idx_respostas_avaliacao', 'respostas_alunos', ['avaliacao_id'], unique=False)
    op.create_index('idx_desempenho_aluno', 'desempenho', ['aluno_id'], unique=False)
    op.create_index('idx_desempenho_materia', 'desempenho', ['materia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_desempenho_materia', table_name='desempenho')
    op.drop_index('idx_desempenho_aluno', table_name='desempenho')
    op.drop_index('idx_respostas_avaliacao', table_name='respostas_alunos')
    op.drop_index('idx_respostas_aluno', table_name='respostas_alunos')
    op.drop_index('idx_questoes_materia', table_name='questoes')
    op.drop_index('idx_inscricoes_materia', table_name='inscricoes')
    op.drop_index('idx_inscricoes_aluno', table_name='inscricoes')

    op.drop_table('respostas_alunos')
    op.drop_table('desempenho')
    op.drop_table('questoes')
    op.drop_table('inscricoes')
    op.drop_table('avaliacoes')
    op.drop_table('materias')
    op.drop_table('professores')
    op.drop_table('alunos')

    # Re-create old tables if downgrading to a state before this migration
    # (This part would typically be handled by the *previous* migration's upgrade,
    # but since we are overriding it, we define the inverse here to allow proper downgrade to the state *before* this refactor).
    op.create_table(
        'usuarios',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('ra', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('tipo_usuario', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
        sa.UniqueConstraint('email', name='usuarios_email_key'),
        sa.UniqueConstraint('ra', name='usuarios_ra_key')
    )
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    
    op.create_table(
        'simulados',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_materia', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('titulo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column('texto_base', sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['id_materia'], ['materias.id'], name='simulados_id_materia_fkey'),
        sa.PrimaryKeyConstraint('id', name='simulados_pkey')
    )
    op.create_table(
        'matriculas',
        sa.Column('id_aluno', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id_materia', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['id_aluno'], ['usuarios.id'], name='matriculas_id_aluno_fkey'),
        sa.ForeignKeyConstraint(['id_materia'], ['materias.id'], name='matriculas_id_materia_fkey'),
        sa.PrimaryKeyConstraint('id_aluno', 'id_materia', name='matriculas_pkey')
    )
    op.create_table(
        'questoes',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_simulado', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('enunciado', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('resposta_correta', sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['id_simulado'], ['simulados.id'], name='questoes_id_simulado_fkey'),
        sa.PrimaryKeyConstraint('id', name='questoes_pkey')
    )
    op.create_table(
        'respostas_alunos',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_aluno', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id_questao', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('resposta_aluno', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('correta', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['id_aluno'], ['usuarios.id'], name='respostas_alunos_id_aluno_fkey'),
        sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], name='respostas_alunos_id_questao_fkey'),
        sa.PrimaryKeyConstraint('id', name='respostas_alunos_pkey')
    )
    op.create_table(
        'desempenho_simulados',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_aluno', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id_simulado', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('nota', sa.REAL(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['id_aluno'], ['usuarios.id'], name='desempenho_simulados_id_aluno_fkey'),
        sa.ForeignKeyConstraint(['id_simulado'], ['simulados.id'], name='desempenho_simulados_id_simulado_fkey'),
        sa.PrimaryKeyConstraint('id', name='desempenho_simulados_pkey')
    )
    # ### end Alembic commands ###
